### PR TITLE
refactoring affiliation field selection and string extraction

### PR DESCRIPTION
**Pull request by fsguenth**

### CODE REVIEW

**Comment by anusharanganathan** [comment]
@fsguenth your changes do not check what type of affiliation id we are extracting. We only want ringgold and ror, and need to keep track of the type. Also, for ror, I am stripping out the url, if the id includes it. Have a look at the [conflicts in models.py](https://github.com/OA-DeepGreen/magnificent-octopus/pull/13/conflicts).

Also, sorry, but I don't understand what you are trying to do in ` _create_aff_string`

**Comment by fsguenth** [comment]
_create_aff_string recursively constructs the affiliation string while excluding the content in label, sub and sup elements (which mark the characters used as visual links between author & affiliation), and the content in institution-id (which contains the identifier number -- this is somewhat unnecessary but as i was already on it i thought i may as well exclude that field too).

i'll have a look at the rest now. as far as i remember i haven't changed anything about the identifier selection process. i can go and resolve the conflicts between your commits in the last week and what i added if you want

**Comment by fsguenth** [comment]
@anusharanganathan 
the affiliation identifier selection is now identical to the current one.

I also added some explanatory comments to _create_aff_string. 
it basically does the same thing as the xpath expression "string()" which gives you the text content of the current element and all descendants, but it excludes the text contained in label, sub, sup and institution-id. to do that, we have to iterate over all descendants and build the string ourselves, which is why it looks so unwieldy.
let me know if that helps

**Comment by fsguenth** [comment]
as far as i can see, the remaining conflicts are the deduplicated code blocks for processing the affiliation fields

**Comment by anusharanganathan** [comment]
> as far as i can see, the remaining conflicts are the deduplicated code blocks for processing the affiliation fields

Thank you. I can merge this. I will take care of the conflicts.

**Review by anusharanganathan — APPROVED** [review]

**Comment by anusharanganathan** [comment]
@fsguenth please can you pull the latest changes from develop onto your fork, and then merge develop in your [institutional-identifiers](https://github.com/fsguenth/magnificent-octopus/tree/institutional-identifiers) branch. As your branch is 13 commits behind, git is not allowing me to merge as our branches are divergent.

For the future, you could ask Stefan to add you to this repository. You will then be able to create a branch and issue a PR against this repo, and I would have permissions to be able to merge

**Comment by anusharanganathan** [comment]
Closing this PR in favour of https://github.com/OA-DeepGreen/magnificent-octopus/pull/14

**Pull request closed without merging**
