### PR TITLE
Institutional id addition fsguenth

### PR DESCRIPTION
**Pull request by fsguenth**
I realized that I do have write access to this repo already, so i just created a new branch on here. We can just merge this and close https://github.com/OA-DeepGreen/magnificent-octopus/pull/13

merging this PR will: refactor the affiliation field selection and introduce an improved string extraction for affiliation data.

### CODE REVIEW

**Comment by fsguenth** [comment]
@anusharanganathan is there a reason this is not yet merged? if so, do let me know and I can fix it.

**Comment by anusharanganathan** [comment]
@fsguenth I am sorry to ping this back to you. I added code to extract ringgold and ror and it seems to have been removed in the PR. Is this intentional, or by mistake? I would like the string extraction improvements, as it will help with exclusion matching.

I expect to see something like these lines - https://github.com/OA-DeepGreen/magnificent-octopus/pull/14/files#diff-10eaed7bcba106069e72aa02fa78716027d215a857c345780be26d634a304ae3L484-L506, where the ror and ringgold is extracted, cleaned and saved

**Comment by fsguenth** [comment]
it is the repeated instances of ringgold and ror extraction that are being removed through refactoring. not the extraction itself. See here: https://github.com/OA-DeepGreen/magnificent-octopus/blob/db3a64e3904d632f50d52653051173cb23bb388f/octopus/modules/epmc/models.py#L483 (even in the link you provided, you can see that it retains the retraction. github for some reason simply matches the third of forth code block to the single instance i my PR retains. (compare lines 591 ff and 485 ff. on your link)

**Comment by anusharanganathan** [comment]
Ah, my bad. Thank you. I should have checked the whole code rather than rely on Github’s diff. I’ll merge it now

**Comment by fsguenth** [comment]
right after deleting the branch, i noticed another issue that cropped up with the springer test data, see https://github.com/OA-DeepGreen/magnificent-octopus/pull/16
I apologize for catching it this late.

**Pull request merged**
